<?php

// Operadores aritmeticos +, -, /, *, **, % ...
// Operadores de incremento ++, -- ...
// Operadores de atribuição +=, -=, /= ...
// Operadores de comparação ==, !=, ===, !===, <>, >, <, <=>, >=, <= ...
// Operadores lógicos &&, ||, !, xor ...

?>